apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  labels:
    purpose: multi-container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]