apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    version: v1
spec:
  containers:
  - name: frontend
    image: nginx
    