apiVersion: v1
kind: Pod
metadata:
  name: resources
  namespace: roboshop
spec:
  containers:
  - name: resources-limit
    image: nginx
    resources:
      memory: "68Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "120m"