apiVersion: v1
kind: Pod
metadata:
  name: my-secretpod
  namespace: roboshop
spec:
  containers:
  - name: my-containers
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
    volumes:
    - name: secret-volume
      secret:
        secretName: my-secrets