apiVersion: v1
kind: Pod
metadata:
  name: my-clusterpod
  namespace: roboshop
  labels:
    app: backend
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80