apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-pod
  namespace: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-frontend
template:
  metadata:
    labels:
      app: ecommerce-frontend
spec:
  containers:
  - name: my-containers
    image: nginx
    ports:
    - containerPort: 80