apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod 
  namespace: roboshop
spec:
  volumes:
  - name: hostpath-storage
    hostPath:
      path: /tmp 
      type: Directory

  containers:
  - name: hostpath-container
    image: nginx
    volumeMounts:
      - name: hostpath-storage
        mountPath: /data
    